config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tags
  root to: 'stats#index'

  resources :items, only: %i[index show]
  resources :boxes do
    resources :items
  end
  resources :places do
    resources :spots
  end

  resources :searches, only: [:index]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include PictureUploader::Attachment(:picture)

  belongs_to :owner, class_name: 'User'
  belongs_to :box, counter_cache: true
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  delegate :code, :spot_code, :place_code, to: :box, prefix: false, allow_nil: true
  delegate :summary, :code, to: :box, prefix: true, allow_nil: true
  delegate :spot, to: :box, prefix: false, allow_nil: true
  delegate :spot_id, to: :box, prefix: false, allow_nil: true

  validates :summary, presence: true

  has_paper_trail on: %i[update destroy]

  scope :order_historical, -> { order(updated_at: :desc) }

  def to_s
    summary
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_box
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items/1
  # GET /items/1.json
  def show; end

  # GET /items/new
  def new
    @item = @box.items.new.decorate
  end

  # GET /items/1/edit
  def edit; end

  # POST /items
  # POST /items.json
  def create
    params[:item][:box_id] = @box.id
    @item_op = ItemOp::Create.call(model_params: item_params, owner: current_user)
    respond_to do |format|
      if @item_op.success?
        @item = @item_op.value!
        format.html { redirect_to box_path(@box, anchor: 'related-list'), notice: t('common.flash.created') }
        format.json { render :show, status: :created, location: @item }
      else
        @item = @item_op.failure.decorate
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item_op = ItemOp::Update.call(model_object: @item, model_params: item_params,
                                   owner: current_user)
    respond_to do |format|
      if @item_op.success?
        @item = @item_op.value!
        format.html { redirect_to [@box, @item], notice: t('common.flash.updated') }
        format.json { render :show, status: :ok, location: @item }
      else
        @item = @item_op.failure.decorate
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item_op = SpotOp::Destroy.call(model_object: @item, owner: current_user)
    respond_to do |format|
      if @item_op.success?
        format.html { redirect_to @box, notice: t('common.flash.destroyed') }
        format.json { head :no_content }
      else
        @item = @item_op.failure
        format.html do
          redirect_to @box, notice: t('common.flash.cannot_destroy'),
                            status: :unprocessable_entity
        end
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def set_box
    @box = Box.find(params[:box_id]).decorate
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id]).decorate
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:box_id, :summary, :picture,
                                 :quantity, :using, tag_ids: [])
  end

  def context_icon
    @context_icon = Icon.css_for(:item)
  end
end

app/views/items/_form.html.slim
= simple_form_for([@box, @item], wrapper: :horizontal_form) do |f|
  = f.input :box_id, 
            collection: @box.spot.boxes.map{ |e| ["#{e.code} - #{e.summary}", e.id] }, 
            input_html: { class: 'form-control form-control-chosen' },
            label: f.object.label_icon(:box_id, :box)
  = f.input :summary
  = f.input :using, as: :boolean, wrapper: :horizontal_boolean_single,
            label: f.object.label_icon(:using, :using)
  = f.input :quantity, label: f.object.label_icon(:quantity, :quantity)
  = f.input :tag_ids, as: :select, collection: Tag.for_select,
    input_html: { multiple: true, class: 'form-control form-control-chosen',
    data: { placeholder: t('simple_form.prompts.options') } },
    label: f.object.label_icon(:tag_ids, :tag)
  = f.input :picture, as: :hidden, input_html: { value: @item.cached_picture_data }
  = f.input :picture, as: :file, wrapper: :custom_file,
            label: f.object.label_icon(:picture, :picture)
  = f.button :submit, class: 'btn-outline-dark'

app/views/items/edit.html.slim
- breadcrumb :item, @box, @item

= intro_actions(summary: t('common.actions.edit', entity: @item)) do
  = link_to_item(@box, @item)
== render 'form'

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Box
      th Summary
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.box
        td = item.summary
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Item', new_item_path

app/views/items/new.html.slim
- breadcrumb :item, @box
- entity = Item.model_name.human(count: 1)
- entities = Item.model_name.human(count: :many)

= intro_actions(summary: t('common.actions.new', entity: entity)) do
  = link_to_item(@box)
== render 'form'

app/views/items/show.html.slim
- breadcrumb :item, @box, @item
- entity = Item.model_name.human(count: :one)
- entities = Item.model_name.human(count: :many)

= intro_actions(summary: Item.model_name.human(count: 1) + ": #{@item}") do
  = link_to_edit(@box, @item)
  = link_to_list(polymorphic_path([@box]), entities: entities)
= detail_row @item, :box_code do
  = @item.badge_fullcode
= detail_row @item, :summary
= detail_row @item, :using do
  = bool_to_icon(@item.using, icon: 'fas fa-external-link-alt')
= detail_row @item, :quantity
= detail_row @item, :tags do
  = raw @item.badge_tags
= detail_row @item, :picture do
  = @item.image_tag_medium
= detail_row @item, :created_at do
  = @item.created_at_long
= detail_row @item, :updated_at do
  = @item.updated_at_long