config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tags
  root to: 'stats#index'

  resources :items, only: %i[index show]
  resources :boxes do
    resources :items
  end
  resources :places do
    resources :spots
  end

  resources :searches, only: [:index]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashes.html.slim
- flash.each do |key, value|
  div class="alert #{flash_level_to_alert_class(key)} #{'alert-dismissible' if dismissible} fade show mt-sm-4 mt-xs-2 mb-2" role="alert"
    = value
    - if dismissible
      button type="button" class="close" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true"
          | &times;

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand.navbar-dark.bg-dark
  = link_to root_path, class: "navbar-brand" do
    - # logo here
  button.navbar-toggler[type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation']
    span.navbar-toggler-icon
  div.collapse.navbar-collapse[id='navbarNavDropdown']
    ul.navbar-nav
      li.nav-item.ml-3
        = link_to searches_path, class: 'nav-link' do
          i.mr-1*{ class: Icon.css_for(:search) }
          = t("common.actions.search")
      li.nav-item.ml-3
        = link_to boxes_path, class: 'nav-link' do
          i.mr-1*{ class: Icon.css_for(:box) }
          = Box.model_name.human(count: 2)
      li.nav-item.ml-3
        = link_to tags_path, class: 'nav-link' do
          i.mr-1*{ class: Icon.css_for(:tag) }
          = Tag.model_name.human(count: 2)
      li.nav-item.ml-3
        = link_to places_path, class: 'nav-link' do
          i.mr-1*{ class: Icon.css_for(:place) }
          = Place.model_name.human(count: 2)
    ul.navbar-nav.ml-auto
      li.nav-item.dropdown
        = link_to '#', class: 'nav-link dropdown-toggle mr-2',
                  id: 'navbarDropdownMenuLink', 'data-toggle' => 'dropdown',
                  'aria-haspopup' => 'true', 'aria-expanded' => 'false' do
                    i.mr-2*{ class: Icon.css_for(:user) }
                    = current_user.full_name
        div.dropdown-menu[aria-labelledby='navbarDropdownMenuLink']
          = link_to destroy_user_session_path, class: 'dropdown-item', method: :delete
            i.mr-2*{ class: Icon.css_for(:log_out) }
            = t('common.actions.sign_out')

app/views/layouts/application.html.slim
doctype 5
html lang="#{I18n.locale}" data-default-locale="#{I18n.default_locale}"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta content="width=device-width, initial-scale=1" name="viewport"
    title Finder
    = favicon_link_tag
    = stylesheet_pack_tag "application", media: "all"
    = javascript_pack_tag "application"
    = csrf_meta_tags
    = csp_meta_tag

  body
    - if current_user.present?
      header= render "layouts/header"
    main.container-fluid.px-0.px-md-2.px-lg-3
      = render "layouts/flashes", dismissible: true
      = h breadcrumbs separator: " &rsaquo; ", style: :bootstrap, class: 'breadcrumb mt-md-3'
      .shadow.p-lg-3.mb-lg-5.bg-white.rounded
        = yield

    footer.footer= render "layouts/footer"